package p000;

import one.p010me.image.crop.view.CropPhotoView;
import one.p010me.sdk.uikit.common.simplepopup.SimpleContextMenuPopupWindow;
import org.apache.http.HttpStatus;
import ru.CryptoPro.JCSP.MSCAPI.HProv;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: classes.dex */
public final class c0h {
    private static final /* synthetic */ dl6 $ENTRIES;
    private static final /* synthetic */ c0h[] $VALUES;
    private final int code;
    public static final c0h APPLICATION_BACKGROUND = new c0h("APPLICATION_BACKGROUND", 0, 1);
    public static final c0h AUTH_SIGN_METHOD = new c0h("AUTH_SIGN_METHOD", 1, 50);
    public static final c0h AUTH_PHONE_LOGIN = new c0h("AUTH_PHONE_LOGIN", 2, 51);
    public static final c0h AUTH_OTP = new c0h("AUTH_OTP", 3, 52);
    public static final c0h AUTH_EMPTY_PROFILE = new c0h("AUTH_EMPTY_PROFILE", 4, 53);
    public static final c0h AUTH_AVATARS = new c0h("AUTH_AVATARS", 5, 54);
    public static final c0h CONTACTS_TAB = new c0h("CONTACTS_TAB", 6, 100);
    public static final c0h CONTACTS_ADD = new c0h("CONTACTS_ADD", 7, 101);
    public static final c0h CONTACTS_SEARCH = new c0h("CONTACTS_SEARCH", 8, 102);
    public static final c0h CONTACTS_SEARCH_BY_PHONE = new c0h("CONTACTS_SEARCH_BY_PHONE", 9, 103);
    public static final c0h CHATS_LIST_TAB = new c0h("CHATS_LIST_TAB", 10, CropPhotoView.GRID_PAINT_ALPHA);
    public static final c0h CHATS_LIST_SEARCH_INITIAL = new c0h("CHATS_LIST_SEARCH_INITIAL", 11, 151);
    public static final c0h CHATS_LIST_SEARCH_RESULT = new c0h("CHATS_LIST_SEARCH_RESULT", 12, 152);
    public static final c0h CREATE_CHAT = new c0h("CREATE_CHAT", 13, 200);
    public static final c0h CREATE_CHAT_MEMBERS_PICKER = new c0h("CREATE_CHAT_MEMBERS_PICKER", 14, HttpStatus.SC_CREATED);
    public static final c0h CREATE_CHAT_INFO = new c0h("CREATE_CHAT_INFO", 15, HttpStatus.SC_ACCEPTED);
    public static final c0h CREATE_CHANNEL_INFO = new c0h("CREATE_CHANNEL_INFO", 16, HttpStatus.SC_NON_AUTHORITATIVE_INFORMATION);
    public static final c0h AVATAR_PICKER_GALLERY = new c0h("AVATAR_PICKER_GALLERY", 17, SimpleContextMenuPopupWindow.MENU_CONSTANT_WIDTH);
    public static final c0h AVATAR_PICKER_CROP = new c0h("AVATAR_PICKER_CROP", 18, 251);
    public static final c0h AVATAR_PICKER_CAMERA = new c0h("AVATAR_PICKER_CAMERA", 19, 252);
    public static final c0h AVATAR_VIEWER = new c0h("AVATAR_VIEWER", 20, 253);
    public static final c0h CALL_HISTORY_TAB = new c0h("CALL_HISTORY_TAB", 21, HttpStatus.SC_MULTIPLE_CHOICES);
    public static final c0h CALL_NEW_CALL = new c0h("CALL_NEW_CALL", 22, HttpStatus.SC_MOVED_TEMPORARILY);
    public static final c0h CALL_CREATE_GROUP_LINK = new c0h("CALL_CREATE_GROUP_LINK", 23, HttpStatus.SC_SEE_OTHER);
    public static final c0h CALL_ADD_PARTICIPANTS = new c0h("CALL_ADD_PARTICIPANTS", 24, HttpStatus.SC_NOT_MODIFIED);
    public static final c0h CALL = new c0h("CALL", 25, HttpStatus.SC_USE_PROXY);
    public static final c0h CALL_JOIN_LINK_PREVIEW = new c0h("CALL_JOIN_LINK_PREVIEW", 26, 306);
    public static final c0h ADMIN_CALL_SETTINGS = new c0h("ADMIN_CALL_SETTINGS", 27, HttpStatus.SC_TEMPORARY_REDIRECT);
    public static final c0h CALL_VPN_WARNING_SHEET = new c0h("CALL_VPN_WARNING_SHEET", 28, 312);
    public static final c0h CHAT = new c0h("CHAT", 29, 350);
    public static final c0h CHAT_ATTACH_PICKER = new c0h("CHAT_ATTACH_PICKER", 30, 351);
    public static final c0h CHAT_ATTACH_PICKER_MEDIA_VIEWER = new c0h("CHAT_ATTACH_PICKER_MEDIA_VIEWER", 31, 352);
    public static final c0h CHAT_ATTACH_PICKER_CAMERA = new c0h("CHAT_ATTACH_PICKER_CAMERA", 32, 353);
    public static final c0h CHAT_SHARE_LOCATION = new c0h("CHAT_SHARE_LOCATION", 33, 354);
    public static final c0h CHAT_SHARE_CONTACT = new c0h("CHAT_SHARE_CONTACT", 34, 355);
    public static final c0h CHAT_VPN_WARNING_SHEET = new c0h("CHAT_VPN_WARNING_SHEET", 35, 356);
    public static final c0h CHAT_FORWARD = new c0h("CHAT_FORWARD", 36, 357);
    public static final c0h CHAT_MEDIA_VIEWER = new c0h("CHAT_MEDIA_VIEWER", 37, 358);
    public static final c0h CHAT_SYSTEM_FILE_VIEWER = new c0h("CHAT_SYSTEM_FILE_VIEWER", 38, 359);
    public static final c0h CHAT_LOCATION_VIEWER = new c0h("CHAT_LOCATION_VIEWER", 39, 360);
    public static final c0h CHAT_INFO = new c0h("CHAT_INFO", 40, HttpStatus.SC_BAD_REQUEST);
    public static final c0h CHAT_INFO_ALL_PARTICIPANTS = new c0h("CHAT_INFO_ALL_PARTICIPANTS", 41, HttpStatus.SC_UNAUTHORIZED);
    public static final c0h CHAT_INFO_EDITING = new c0h("CHAT_INFO_EDITING", 42, HttpStatus.SC_PAYMENT_REQUIRED);
    public static final c0h CHAT_INFO_ADD_PARTICIPANTS = new c0h("CHAT_INFO_ADD_PARTICIPANTS", 43, HttpStatus.SC_FORBIDDEN);
    public static final c0h CHAT_INFO_ADMINISTRATORS = new c0h("CHAT_INFO_ADMINISTRATORS", 44, HttpStatus.SC_NOT_FOUND);
    public static final c0h CHAT_INFO_ADD_ADMINISTRATOR = new c0h("CHAT_INFO_ADD_ADMINISTRATOR", 45, HttpStatus.SC_METHOD_NOT_ALLOWED);
    public static final c0h CHAT_INFO_BLOCKED_PARTICIPANTS = new c0h("CHAT_INFO_BLOCKED_PARTICIPANTS", 46, HttpStatus.SC_NOT_ACCEPTABLE);
    public static final c0h CHAT_INFO_CHANGE_OWNER = new c0h("CHAT_INFO_CHANGE_OWNER", 47, HttpStatus.SC_PROXY_AUTHENTICATION_REQUIRED);
    public static final c0h CHAT_ATTACHMENTS_MEDIA = new c0h("CHAT_ATTACHMENTS_MEDIA", 48, HttpStatus.SC_REQUEST_TIMEOUT);
    public static final c0h CHAT_ATTACHMENTS_FILES = new c0h("CHAT_ATTACHMENTS_FILES", 49, HttpStatus.SC_CONFLICT);
    public static final c0h CHAT_ATTACHMENTS_LINKS = new c0h("CHAT_ATTACHMENTS_LINKS", 50, HttpStatus.SC_GONE);
    public static final c0h CHAT_INFO_INVITE_LINK = new c0h("CHAT_INFO_INVITE_LINK", 51, HttpStatus.SC_LENGTH_REQUIRED);
    public static final c0h CHAT_LINK_EDITING = new c0h("CHAT_LINK_EDITING", 52, HttpStatus.SC_REQUEST_TOO_LONG);
    public static final c0h SETTINGS_TAB = new c0h("SETTINGS_TAB", 53, 450);
    public static final c0h SETTINGS_PROFILE_EDITING = new c0h("SETTINGS_PROFILE_EDITING", 54, 451);
    public static final c0h SETTINGS_SHORTNAME_CHANGE = new c0h("SETTINGS_SHORTNAME_CHANGE", 55, 452);
    public static final c0h SETTINGS_PHONE_CHANGE = new c0h("SETTINGS_PHONE_CHANGE", 56, 453);
    public static final c0h SETTINGS_NOTIFICATIONS = new c0h("SETTINGS_NOTIFICATIONS", 57, 454);
    public static final c0h SETTINGS_NOTIFICATIONS_SYSTEM = new c0h("SETTINGS_NOTIFICATIONS_SYSTEM", 58, 455);
    public static final c0h SETTINGS_FOLDERS = new c0h("SETTINGS_FOLDERS", 59, 456);
    public static final c0h SETTINGS_PRIVACY = new c0h("SETTINGS_PRIVACY", 60, 457);
    public static final c0h SETTINGS_PRIVACY_BLOCK_LIST = new c0h("SETTINGS_PRIVACY_BLOCK_LIST", 61, 458);
    public static final c0h SETTINGS_MEDIA = new c0h("SETTINGS_MEDIA", 62, 459);
    public static final c0h SETTINGS_MESSAGES = new c0h("SETTINGS_MESSAGES", 63, 460);
    public static final c0h SETTINGS_STICKERS = new c0h("SETTINGS_STICKERS", 64, 461);
    public static final c0h SETTINGS_CHAT_DECORATION = new c0h("SETTINGS_CHAT_DECORATION", 65, 462);
    public static final c0h SETTINGS_PHONE_CHANGE_PHONE_INPUT = new c0h("SETTINGS_PHONE_CHANGE_PHONE_INPUT", 66, 463);
    public static final c0h SETTINGS_PHONE_CHANGE_PHONE_OTP = new c0h("SETTINGS_PHONE_CHANGE_PHONE_OTP", 67, 464);
    public static final c0h SETTINGS_CACHE = new c0h("SETTINGS_CACHE", 68, 465);
    public static final c0h SETTINGS_PROFILE_AVATARS = new c0h("SETTINGS_PROFILE_AVATARS", 69, 466);
    public static final c0h SETTINGS_PRIVACY_SAFE_MODE = new c0h("SETTINGS_PRIVACY_SAFE_MODE", 70, 468);
    public static final c0h SETTINGS_PRIVACY_NEW_PINCODE = new c0h("SETTINGS_PRIVACY_NEW_PINCODE", 71, 469);
    public static final c0h SETTINGS_PRIVACY_ACCEPT_PINCODE = new c0h("SETTINGS_PRIVACY_ACCEPT_PINCODE", 72, 470);
    public static final c0h SETTINGS_PRIVACY_INSERT_PINCODE = new c0h("SETTINGS_PRIVACY_INSERT_PINCODE", 73, 471);
    public static final c0h SETTINGS_PRIVACY_SAFE_MODE_CALLS = new c0h("SETTINGS_PRIVACY_SAFE_MODE_CALLS", 74, 472);
    public static final c0h SETTINGS_PRIVACY_SAFE_MODE_INVITE = new c0h("SETTINGS_PRIVACY_SAFE_MODE_INVITE", 75, 473);
    public static final c0h SETTINGS_PRIVACY_SAFE_MODE_ONLINE = new c0h("SETTINGS_PRIVACY_SAFE_MODE_ONLINE", 76, 474);
    public static final c0h SETTINGS_PRIVACY_SAFE_MODE_SEARCH_BY_PHONE = new c0h("SETTINGS_PRIVACY_SAFE_MODE_SEARCH_BY_PHONE", 77, 475);
    public static final c0h SETTINGS_PRIVACY_MINIAPPS = new c0h("SETTINGS_PRIVACY_MINIAPPS", 78, 476);
    public static final c0h SETTINGS_PRIVACY_MINIAPP = new c0h("SETTINGS_PRIVACY_MINIAPP", 79, 477);
    public static final c0h SETTINGS_PRIVACY_SENSITIVE_CONTENT = new c0h("SETTINGS_PRIVACY_SENSITIVE_CONTENT", 80, 479);
    public static final c0h SETTINGS_RINGTONE = new c0h("SETTINGS_RINGTONE", 81, 480);
    public static final c0h SETTINGS_DEVICES = new c0h("SETTINGS_DEVICES", 82, 481);
    public static final c0h SETTINGS_DEVICES_QR_SCANER = new c0h("SETTINGS_DEVICES_QR_SCANER", 83, 482);
    public static final c0h SETTINGS_LOCALE = new c0h("SETTINGS_LOCALE", 84, 483);
    public static final c0h SETTINGS_PRIVACY_PHONE_NUMBER = new c0h("SETTINGS_PRIVACY_PHONE_NUMBER", 85, 484);
    public static final c0h MINIAPP = new c0h("MINIAPP", 86, 500);
    public static final c0h MINIAPP_CAMERA_PERMISSION = new c0h("MINIAPP_CAMERA_PERMISSION", 87, HttpStatus.SC_NOT_IMPLEMENTED);
    public static final c0h MINIAPP_SETTINGS_CAMERA_PERMISSION = new c0h("MINIAPP_SETTINGS_CAMERA_PERMISSION", 88, HttpStatus.SC_BAD_GATEWAY);
    public static final c0h MINIAPP_CAMERA = new c0h("MINIAPP_CAMERA", 89, HttpStatus.SC_SERVICE_UNAVAILABLE);
    public static final c0h MINIAPP_QR_SCANNER = new c0h("MINIAPP_QR_SCANNER", 90, HttpStatus.SC_GATEWAY_TIMEOUT);
    public static final c0h MINIAPP_PICKER_GALLERY = new c0h("MINIAPP_PICKER_GALLERY", 91, HttpStatus.SC_HTTP_VERSION_NOT_SUPPORTED);
    public static final c0h MINIAPP_ERROR = new c0h("MINIAPP_ERROR", 92, 506);
    public static final c0h SETTINGS_2FA_PASSWORD_INPUT = new c0h("SETTINGS_2FA_PASSWORD_INPUT", 93, 750);
    public static final c0h SETTINGS_2FA = new c0h("SETTINGS_2FA", 94, 751);
    public static final c0h SETTINGS_2FA_PASSWORD_CHANGE = new c0h("SETTINGS_2FA_PASSWORD_CHANGE", 95, 752);
    public static final c0h SETTINGS_2FA_PASSWORD_DROP = new c0h("SETTINGS_2FA_PASSWORD_DROP", 96, 753);
    public static final c0h SETTINGS_2FA_CHANGE_EMAIL = new c0h("SETTINGS_2FA_CHANGE_EMAIL", 97, 754);
    public static final c0h SETTINGS_2FA_EMAIL_CODE = new c0h("SETTINGS_2FA_EMAIL_CODE", 98, 755);
    public static final c0h SETTINGS_2FA_EMAIL_SET = new c0h("SETTINGS_2FA_EMAIL_SET", 99, 756);
    public static final c0h SETTINGS_2FA_PASSWORD_RESET_INPUT_NEW = new c0h("SETTINGS_2FA_PASSWORD_RESET_INPUT_NEW", 100, 757);
    public static final c0h SETTINGS_2FA_PROFILE_DELETE = new c0h("SETTINGS_2FA_PROFILE_DELETE", 101, 758);
    public static final c0h SETTINGS_2FA_PROFILE_DELETE_STOP = new c0h("SETTINGS_2FA_PROFILE_DELETE_STOP", 102, 759);
    public static final c0h AUTH_2FA_PASSWORD_CREATE = new c0h("AUTH_2FA_PASSWORD_CREATE", 103, 760);
    public static final c0h AUTH_2FA_SUGGEST = new c0h("AUTH_2FA_SUGGEST", 104, 761);
    public static final c0h AUTH_2FA_EMAIL = new c0h("AUTH_2FA_EMAIL", 105, 762);
    public static final c0h AUTH_2FA_EMAIL_CODE = new c0h("AUTH_2FA_EMAIL_CODE", 106, 763);
    public static final c0h AUTH_2FA_SUCCESS = new c0h("AUTH_2FA_SUCCESS", HProv.PP_SET_PIN, 764);
    public static final c0h AUTH_2FA_PASSWORD_INPUT = new c0h("AUTH_2FA_PASSWORD_INPUT", 108, 765);
    public static final c0h AUTH_2FA_START = new c0h("AUTH_2FA_START", 109, 766);
    public static final c0h SETTINGS_2FA_PASSWORD_RESET_EMAIL_CODE = new c0h("SETTINGS_2FA_PASSWORD_RESET_EMAIL_CODE", 110, 767);

    static {
        c0h[] m18140c = m18140c();
        $VALUES = m18140c;
        $ENTRIES = el6.m30428a(m18140c);
    }

    public c0h(String str, int i, int i2) {
        this.code = i2;
    }

    /* renamed from: c */
    public static final /* synthetic */ c0h[] m18140c() {
        return new c0h[]{APPLICATION_BACKGROUND, AUTH_SIGN_METHOD, AUTH_PHONE_LOGIN, AUTH_OTP, AUTH_EMPTY_PROFILE, AUTH_AVATARS, CONTACTS_TAB, CONTACTS_ADD, CONTACTS_SEARCH, CONTACTS_SEARCH_BY_PHONE, CHATS_LIST_TAB, CHATS_LIST_SEARCH_INITIAL, CHATS_LIST_SEARCH_RESULT, CREATE_CHAT, CREATE_CHAT_MEMBERS_PICKER, CREATE_CHAT_INFO, CREATE_CHANNEL_INFO, AVATAR_PICKER_GALLERY, AVATAR_PICKER_CROP, AVATAR_PICKER_CAMERA, AVATAR_VIEWER, CALL_HISTORY_TAB, CALL_NEW_CALL, CALL_CREATE_GROUP_LINK, CALL_ADD_PARTICIPANTS, CALL, CALL_JOIN_LINK_PREVIEW, ADMIN_CALL_SETTINGS, CALL_VPN_WARNING_SHEET, CHAT, CHAT_ATTACH_PICKER, CHAT_ATTACH_PICKER_MEDIA_VIEWER, CHAT_ATTACH_PICKER_CAMERA, CHAT_SHARE_LOCATION, CHAT_SHARE_CONTACT, CHAT_VPN_WARNING_SHEET, CHAT_FORWARD, CHAT_MEDIA_VIEWER, CHAT_SYSTEM_FILE_VIEWER, CHAT_LOCATION_VIEWER, CHAT_INFO, CHAT_INFO_ALL_PARTICIPANTS, CHAT_INFO_EDITING, CHAT_INFO_ADD_PARTICIPANTS, CHAT_INFO_ADMINISTRATORS, CHAT_INFO_ADD_ADMINISTRATOR, CHAT_INFO_BLOCKED_PARTICIPANTS, CHAT_INFO_CHANGE_OWNER, CHAT_ATTACHMENTS_MEDIA, CHAT_ATTACHMENTS_FILES, CHAT_ATTACHMENTS_LINKS, CHAT_INFO_INVITE_LINK, CHAT_LINK_EDITING, SETTINGS_TAB, SETTINGS_PROFILE_EDITING, SETTINGS_SHORTNAME_CHANGE, SETTINGS_PHONE_CHANGE, SETTINGS_NOTIFICATIONS, SETTINGS_NOTIFICATIONS_SYSTEM, SETTINGS_FOLDERS, SETTINGS_PRIVACY, SETTINGS_PRIVACY_BLOCK_LIST, SETTINGS_MEDIA, SETTINGS_MESSAGES, SETTINGS_STICKERS, SETTINGS_CHAT_DECORATION, SETTINGS_PHONE_CHANGE_PHONE_INPUT, SETTINGS_PHONE_CHANGE_PHONE_OTP, SETTINGS_CACHE, SETTINGS_PROFILE_AVATARS, SETTINGS_PRIVACY_SAFE_MODE, SETTINGS_PRIVACY_NEW_PINCODE, SETTINGS_PRIVACY_ACCEPT_PINCODE, SETTINGS_PRIVACY_INSERT_PINCODE, SETTINGS_PRIVACY_SAFE_MODE_CALLS, SETTINGS_PRIVACY_SAFE_MODE_INVITE, SETTINGS_PRIVACY_SAFE_MODE_ONLINE, SETTINGS_PRIVACY_SAFE_MODE_SEARCH_BY_PHONE, SETTINGS_PRIVACY_MINIAPPS, SETTINGS_PRIVACY_MINIAPP, SETTINGS_PRIVACY_SENSITIVE_CONTENT, SETTINGS_RINGTONE, SETTINGS_DEVICES, SETTINGS_DEVICES_QR_SCANER, SETTINGS_LOCALE, SETTINGS_PRIVACY_PHONE_NUMBER, MINIAPP, MINIAPP_CAMERA_PERMISSION, MINIAPP_SETTINGS_CAMERA_PERMISSION, MINIAPP_CAMERA, MINIAPP_QR_SCANNER, MINIAPP_PICKER_GALLERY, MINIAPP_ERROR, SETTINGS_2FA_PASSWORD_INPUT, SETTINGS_2FA, SETTINGS_2FA_PASSWORD_CHANGE, SETTINGS_2FA_PASSWORD_DROP, SETTINGS_2FA_CHANGE_EMAIL, SETTINGS_2FA_EMAIL_CODE, SETTINGS_2FA_EMAIL_SET, SETTINGS_2FA_PASSWORD_RESET_INPUT_NEW, SETTINGS_2FA_PROFILE_DELETE, SETTINGS_2FA_PROFILE_DELETE_STOP, AUTH_2FA_PASSWORD_CREATE, AUTH_2FA_SUGGEST, AUTH_2FA_EMAIL, AUTH_2FA_EMAIL_CODE, AUTH_2FA_SUCCESS, AUTH_2FA_PASSWORD_INPUT, AUTH_2FA_START, SETTINGS_2FA_PASSWORD_RESET_EMAIL_CODE};
    }

    public static c0h valueOf(String str) {
        return (c0h) Enum.valueOf(c0h.class, str);
    }

    public static c0h[] values() {
        return (c0h[]) $VALUES.clone();
    }

    /* renamed from: h */
    public final int m18141h() {
        return this.code;
    }
}
