package ru.CryptoPro.JCSP;

import java.util.Map;
import ru.CryptoPro.JCP.JCP;
import ru.CryptoPro.JCP.params.AlgIdSpecForeign;
import ru.CryptoPro.JCP.params.OID;
import ru.CryptoPro.JCSP.Cipher.GostCipher;
import ru.CryptoPro.JCSP.KeyStore.KeyStoreConfigBase;
import ru.CryptoPro.JCSP.KeyStore.KeyStoreConfigRSA;

/* loaded from: classes5.dex */
public class JCSPRSA extends JCSP {
    public static final String INFO = "CryptoPro Java CSP RSA Provider (RSA, AES, 3DES, SHA)";
    public static final String PROVIDER_NAME = "JCSPRSA";

    public JCSPRSA() {
        super("JCSPRSA", JCSP.getJarVersion().getProductVersion().doubleValue(), INFO, 24);
    }

    @Override // ru.CryptoPro.JCSP.JCSP
    public String ProviderName() {
        return "JCSPRSA";
    }

    @Override // ru.CryptoPro.JCSP.JCSP
    /* renamed from: a */
    public KeyStoreConfigBase mo90554a() {
        return KeyStoreConfigRSA.getInstance();
    }

    @Override // ru.CryptoPro.JCSP.JCSP
    /* renamed from: c */
    public void mo90559c(Map map) {
        map.put("MessageDigest.SHA1 implementedIn", "Software");
        map.put("MessageDigest.SHA1", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA1Digest");
        map.put("MessageDigest.CP_SHA1 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA1", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA1Digest");
        map.put("Alg.Alias.MessageDigest.1.3.14.3.2.26", JCP.DIGEST_CP_SHA1);
        map.put("Alg.Alias.MessageDigest.OID.1.3.14.3.2.26", JCP.DIGEST_CP_SHA1);
        map.put("MessageDigest.SHA224 implementedIn", "Software");
        map.put("MessageDigest.SHA224", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA224Digest");
        map.put("MessageDigest.CP_SHA224 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA224", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA224Digest");
        map.put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.4", JCP.DIGEST_CP_SHA224);
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.4", JCP.DIGEST_CP_SHA224);
        map.put("MessageDigest.SHA256 implementedIn", "Software");
        map.put("MessageDigest.SHA256", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA256Digest");
        map.put("MessageDigest.CP_SHA256 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA256", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA256Digest");
        map.put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.1", JCP.DIGEST_CP_SHA256);
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.1", JCP.DIGEST_CP_SHA256);
        map.put("MessageDigest.SHA384 implementedIn", "Software");
        map.put("MessageDigest.SHA384", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA384Digest");
        map.put("MessageDigest.CP_SHA384 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA384", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA384Digest");
        map.put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.2", JCP.DIGEST_CP_SHA384);
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.2", JCP.DIGEST_CP_SHA384);
        map.put("MessageDigest.SHA512 implementedIn", "Software");
        map.put("MessageDigest.SHA512", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA512Digest");
        map.put("MessageDigest.CP_SHA512 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA512", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA512Digest");
        map.put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.3", JCP.DIGEST_CP_SHA512);
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.3", JCP.DIGEST_CP_SHA512);
        map.put("MessageDigest.SHA-1 implementedIn", "Software");
        map.put("MessageDigest.SHA-1", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA1Digest");
        map.put("MessageDigest.SHA-224 implementedIn", "Software");
        map.put("MessageDigest.SHA-224", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA_224Digest");
        map.put("MessageDigest.CP_SHA-224 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA-224", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA_224Digest");
        map.put("MessageDigest.SHA-256 implementedIn", "Software");
        map.put("MessageDigest.SHA-256", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA_256Digest");
        map.put("MessageDigest.CP_SHA-256 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA-256", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA_256Digest");
        map.put("MessageDigest.SHA-384 implementedIn", "Software");
        map.put("MessageDigest.SHA-384", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA_384Digest");
        map.put("MessageDigest.CP_SHA-384 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA-384", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA_384Digest");
        map.put("MessageDigest.SHA-512 implementedIn", "Software");
        map.put("MessageDigest.SHA-512", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA_512Digest");
        map.put("MessageDigest.CP_SHA-512 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA-512", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA_512Digest");
        map.put("MessageDigest.SHA3-224 implementedIn", "Software");
        map.put("MessageDigest.SHA3-224", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_224Digest");
        map.put("MessageDigest.CP_SHA3-224 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA3-224", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_224Digest");
        map.put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.7", JCP.DIGEST_CP_SHA3_224);
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.7", JCP.DIGEST_CP_SHA3_224);
        map.put("MessageDigest.SHA3-256 implementedIn", "Software");
        map.put("MessageDigest.SHA3-256", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_256Digest");
        map.put("MessageDigest.CP_SHA3-256 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA3-256", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_256Digest");
        map.put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.8", JCP.DIGEST_CP_SHA3_256);
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.8", JCP.DIGEST_CP_SHA3_256);
        map.put("MessageDigest.SHA3-384 implementedIn", "Software");
        map.put("MessageDigest.SHA3-384", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_384Digest");
        map.put("MessageDigest.CP_SHA3-384 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA3-384", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_384Digest");
        map.put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.9", JCP.DIGEST_CP_SHA3_384);
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.9", JCP.DIGEST_CP_SHA3_384);
        map.put("MessageDigest.SHA3-512 implementedIn", "Software");
        map.put("MessageDigest.SHA3-512", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_512Digest");
        map.put("MessageDigest.CP_SHA3-512 implementedIn", "Software");
        map.put("MessageDigest.CP_SHA3-512", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_512Digest");
        map.put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.10", JCP.DIGEST_CP_SHA3_512);
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.10", JCP.DIGEST_CP_SHA3_512);
        map.put("Mac.HMAC_SHA1", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA1Hmac");
        map.put("Mac.HmacSHA1", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA1Hmac");
        map.put("Alg.Alias.Mac.1.2.840.113549.2.7", "HMAC_SHA1");
        map.put("Alg.Alias.MessageDigest.OID.1.2.840.113549.2.7", "HMAC_SHA1");
        map.put("Mac.HMAC_SHA224", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA224Hmac");
        map.put("Mac.HmacSHA224", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA224Hmac");
        map.put("Alg.Alias.Mac.1.2.840.113549.2.8", "HMAC_SHA224");
        map.put("Alg.Alias.MessageDigest.OID.1.2.840.113549.2.8", "HMAC_SHA224");
        map.put("Mac.HMAC_SHA256", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA256Hmac");
        map.put("Mac.HmacSHA256", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA256Hmac");
        map.put("Alg.Alias.Mac.1.2.840.113549.2.9", "HMAC_SHA256");
        map.put("Alg.Alias.MessageDigest.OID.1.2.840.113549.2.9", "HMAC_SHA256");
        map.put("Mac.HMAC_SHA384", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA384Hmac");
        map.put("Mac.HmacSHA384", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA384Hmac");
        map.put("Alg.Alias.Mac.1.2.840.113549.2.10", "HMAC_SHA384");
        map.put("Alg.Alias.MessageDigest.OID.1.2.840.113549.2.10", "HMAC_SHA384");
        map.put("Mac.HMAC_SHA512", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA512Hmac");
        map.put("Mac.HmacSHA512", "ru.CryptoPro.JCSP.Digest.sha.JCSPSHA512Hmac");
        map.put("Alg.Alias.Mac.1.2.840.113549.2.11", "HMAC_SHA512");
        map.put("Alg.Alias.MessageDigest.OID.1.2.840.113549.2.11", "HMAC_SHA512");
        map.put("Mac.HMAC_SHA3_224", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_224Hmac");
        map.put("Alg.Alias.Mac.2.16.840.1.101.3.4.2.13", "HMAC_SHA3_224");
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.13", "HMAC_SHA3_224");
        map.put("Mac.HMAC_SHA3_256", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_256Hmac");
        map.put("Alg.Alias.Mac.2.16.840.1.101.3.4.2.14", "HMAC_SHA3_256");
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.14", "HMAC_SHA3_256");
        map.put("Mac.HMAC_SHA3_384", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_384Hmac");
        map.put("Alg.Alias.Mac.2.16.840.1.101.3.4.2.15", "HMAC_SHA3_384");
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.15", "HMAC_SHA3_384");
        map.put("Mac.HMAC_SHA3_512", "ru.CryptoPro.JCSP.Digest.sha3.JCSPSHA3_512Hmac");
        map.put("Alg.Alias.Mac.2.16.840.1.101.3.4.2.16", "HMAC_SHA3_512");
        map.put("Alg.Alias.MessageDigest.OID.2.16.840.1.101.3.4.2.16", "HMAC_SHA3_512");
        map.put("Mac.DES_MAC", "ru.CryptoPro.JCSP.Cipher.foreign.DESMac");
        map.put("Mac.CP_DES_MAC", "ru.CryptoPro.JCSP.Cipher.foreign.DESMac");
        map.put("Mac.AES_MAC", "ru.CryptoPro.JCSP.Cipher.foreign.AESMac");
        map.put("Mac.CP_AES_MAC", "ru.CryptoPro.JCSP.Cipher.foreign.AESMac");
        map.put("Mac.ANSI_X9_19_ZERO_PADDING", "ru.CryptoPro.JCSP.Cipher.foreign.X9_19_Mac_ZeroPadding");
        map.put("Mac.ANSI_X9_19_IEC_7816_4_PADDING", "ru.CryptoPro.JCSP.Cipher.foreign.X9_19_Mac_IecPadding");
        map.put("Signature.SHA1withRSA implementedIn", "Software");
        map.put("Signature.CryptoProSHA1withRSA implementedIn", "Software");
        map.put("Signature.SHA1withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA1RSASign");
        map.put("Signature.CryptoProSHA1withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA1RSASign");
        map.put("Signature.CP_SHA1withRSA implementedIn", "Software");
        map.put("Signature.CP_SHA1withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA1RSASign");
        map.put("Alg.Alias.Signature.OID.1.3.14.3.2.29", JCP.SIGN_CP_SHA1_RSA_NAME);
        map.put("Alg.Alias.Signature.1.3.14.3.2.29", JCP.SIGN_CP_SHA1_RSA_NAME);
        map.put("Alg.Alias.Signature." + JCP.SIGN_SHA1_RSA_OID_WITH, JCP.SIGN_CP_SHA1_RSA_NAME);
        map.put("Signature.SHA224withRSA implementedIn", "Software");
        map.put("Signature.CryptoProSHA224withRSA implementedIn", "Software");
        map.put("Signature.SHA224withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA224RSASign");
        map.put("Signature.CryptoProSHA224withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA224RSASign");
        map.put("Signature.CP_SHA224withRSA implementedIn", "Software");
        map.put("Signature.CP_SHA224withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA224RSASign");
        map.put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.14", JCP.SIGN_CP_SHA224_RSA_NAME);
        map.put("Alg.Alias.Signature.1.2.840.113549.1.1.14", JCP.SIGN_CP_SHA224_RSA_NAME);
        map.put("Alg.Alias.Signature." + JCP.SIGN_SHA224_RSA_OID_WITH, JCP.SIGN_CP_SHA224_RSA_NAME);
        map.put("Signature.SHA256withRSA implementedIn", "Software");
        map.put("Signature.CryptoProSHA256withRSA implementedIn", "Software");
        map.put("Signature.SHA256withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA256RSASign");
        map.put("Signature.CryptoProSHA256withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA256RSASign");
        map.put("Signature.CP_SHA256withRSA implementedIn", "Software");
        map.put("Signature.CP_SHA256withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA256RSASign");
        map.put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.11", JCP.SIGN_CP_SHA256_RSA_NAME);
        map.put("Alg.Alias.Signature.1.2.840.113549.1.1.11", JCP.SIGN_CP_SHA256_RSA_NAME);
        map.put("Alg.Alias.Signature." + JCP.SIGN_SHA256_RSA_OID_WITH, JCP.SIGN_CP_SHA256_RSA_NAME);
        map.put("Signature.SHA384withRSA implementedIn", "Software");
        map.put("Signature.CryptoProSHA384withRSA implementedIn", "Software");
        map.put("Signature.SHA384withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA384RSASign");
        map.put("Signature.CryptoProSHA384withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA384RSASign");
        map.put("Signature.CP_SHA384withRSA implementedIn", "Software");
        map.put("Signature.CP_SHA384withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA384RSASign");
        map.put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.12", JCP.SIGN_CP_SHA384_RSA_NAME);
        map.put("Alg.Alias.Signature.1.2.840.113549.1.1.12", JCP.SIGN_CP_SHA384_RSA_NAME);
        map.put("Alg.Alias.Signature." + JCP.SIGN_SHA384_RSA_OID_WITH, JCP.SIGN_CP_SHA384_RSA_NAME);
        map.put("Signature.SHA512withRSA implementedIn", "Software");
        map.put("Signature.CryptoProSHA512withRSA implementedIn", "Software");
        map.put("Signature.SHA512withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA512RSASign");
        map.put("Signature.CryptoProSHA512withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA512RSASign");
        map.put("Signature.CP_SHA512withRSA implementedIn", "Software");
        map.put("Signature.CP_SHA512withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA512RSASign");
        map.put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.13", JCP.SIGN_CP_SHA512_RSA_NAME);
        map.put("Alg.Alias.Signature.1.2.840.113549.1.1.13", JCP.SIGN_CP_SHA512_RSA_NAME);
        map.put("Alg.Alias.Signature." + JCP.SIGN_SHA512_RSA_OID_WITH, JCP.SIGN_CP_SHA512_RSA_NAME);
        if (CSPVersionDependentAlgorithms.isSHA3Supported()) {
            map.put("Signature.SHA3-224withRSA implementedIn", "Software");
            map.put("Signature.CryptoProSHA3-224withRSA implementedIn", "Software");
            map.put("Signature.SHA3-224withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA3_224RSASign");
            map.put("Signature.CryptoProSHA3-224withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA3_224RSASign");
            map.put("Signature.CP_SHA3-224withRSA implementedIn", "Software");
            map.put("Signature.CP_SHA3-224withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA3_224RSASign");
            map.put("Alg.Alias.Signature.OID.2.16.840.1.101.3.4.3.13", JCP.SIGN_CP_SHA3_224_RSA_NAME);
            map.put("Alg.Alias.Signature.2.16.840.1.101.3.4.3.13", JCP.SIGN_CP_SHA3_224_RSA_NAME);
            map.put("Alg.Alias.Signature." + JCP.SIGN_SHA3_224_RSA_OID_WITH, JCP.SIGN_CP_SHA3_224_RSA_NAME);
            map.put("Signature.SHA3-256withRSA implementedIn", "Software");
            map.put("Signature.CryptoProSHA3-256withRSA implementedIn", "Software");
            map.put("Signature.SHA3-256withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA3_256RSASign");
            map.put("Signature.CryptoProSHA3-256withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA3_256RSASign");
            map.put("Signature.CP_SHA3-256withRSA implementedIn", "Software");
            map.put("Signature.CP_SHA3-256withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA3_256RSASign");
            map.put("Alg.Alias.Signature.OID.2.16.840.1.101.3.4.3.14", JCP.SIGN_CP_SHA3_256_RSA_NAME);
            map.put("Alg.Alias.Signature.2.16.840.1.101.3.4.3.14", JCP.SIGN_CP_SHA3_256_RSA_NAME);
            map.put("Alg.Alias.Signature." + JCP.SIGN_SHA3_256_RSA_OID_WITH, JCP.SIGN_CP_SHA3_256_RSA_NAME);
            map.put("Signature.SHA3-384withRSA implementedIn", "Software");
            map.put("Signature.CryptoProSHA3-384withRSA implementedIn", "Software");
            map.put("Signature.SHA3-384withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA3_384RSASign");
            map.put("Signature.CryptoProSHA3-384withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA3_384RSASign");
            map.put("Signature.CP_SHA3-384withRSA implementedIn", "Software");
            map.put("Signature.CP_SHA3-384withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA3_384RSASign");
            map.put("Alg.Alias.Signature.OID.2.16.840.1.101.3.4.3.15", JCP.SIGN_CP_SHA3_384_RSA_NAME);
            map.put("Alg.Alias.Signature.2.16.840.1.101.3.4.3.15", JCP.SIGN_CP_SHA3_384_RSA_NAME);
            map.put("Alg.Alias.Signature." + JCP.SIGN_SHA3_384_RSA_OID_WITH, JCP.SIGN_CP_SHA3_384_RSA_NAME);
            map.put("Signature.SHA3-512withRSA implementedIn", "Software");
            map.put("Signature.CryptoProSHA3-512withRSA implementedIn", "Software");
            map.put("Signature.SHA3-512withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA3_512RSASign");
            map.put("Signature.CryptoProSHA3-512withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPCryptoProSHA3_512RSASign");
            map.put("Signature.CP_SHA3-512withRSA implementedIn", "Software");
            map.put("Signature.CP_SHA3-512withRSA", "ru.CryptoPro.JCSP.Sign.rsa.JCSPSHA3_512RSASign");
            map.put("Alg.Alias.Signature.OID.2.16.840.1.101.3.4.3.16", JCP.SIGN_CP_SHA3_512_RSA_NAME);
            map.put("Alg.Alias.Signature.2.16.840.1.101.3.4.3.16", JCP.SIGN_CP_SHA3_512_RSA_NAME);
            map.put("Alg.Alias.Signature." + JCP.SIGN_SHA3_512_RSA_OID_WITH, JCP.SIGN_CP_SHA3_512_RSA_NAME);
        }
        map.put("KeyPairGenerator.RSA implementedIn", "Software");
        map.put("AlgorithmParameters.RSA implementedIn", "Software");
        map.put("KeyPairGenerator.RSA", "ru.CryptoPro.JCSP.Key.rsa.JCSPRSAKeyPairGenerator");
        map.put("KeyPairGenerator.CP_RSA implementedIn", "Software");
        map.put("AlgorithmParameters.CP_RSA implementedIn", "Software");
        map.put("KeyPairGenerator.CP_RSA", "ru.CryptoPro.JCSP.Key.rsa.JCSPRSAKeyPairGenerator");
        StringBuilder sb = new StringBuilder();
        sb.append("Alg.Alias.KeyPairGenerator.");
        OID oid = AlgIdSpecForeign.OID_RSA;
        sb.append(oid);
        map.put(sb.toString(), "CP_RSA");
        map.put("Alg.Alias.KeyPairGenerator.OID." + oid, "CP_RSA");
        map.put("KeyGenerator.AES", "ru.CryptoPro.JCSP.Key.foreign.JCSPAesKeyGenerator");
        map.put("KeyGenerator.CP_AES", "ru.CryptoPro.JCSP.Key.foreign.JCSPAesKeyGenerator");
        map.put("KeyGenerator.DES", "ru.CryptoPro.JCSP.Key.foreign.JCSPDesKeyGenerator");
        map.put("KeyGenerator.CP_DES", "ru.CryptoPro.JCSP.Key.foreign.JCSPDesKeyGenerator");
        map.put("KeyGenerator.3DES", "ru.CryptoPro.JCSP.Key.foreign.JCSP3DesKeyGenerator");
        map.put("KeyGenerator.CP_3DES", "ru.CryptoPro.JCSP.Key.foreign.JCSP3DesKeyGenerator");
        map.put("KeyGenerator.3DES_112", "ru.CryptoPro.JCSP.Key.foreign.JCSP3DesKeyGenerator");
        map.put("KeyGenerator.CP_3DES_112", "ru.CryptoPro.JCSP.Key.foreign.JCSP3DesKeyGenerator");
        map.put("KeyGenerator.DESede", "ru.CryptoPro.JCSP.Key.foreign.JCSP3DesKeyGenerator");
        map.put("KeyGenerator.TripleDES", "ru.CryptoPro.JCSP.Key.foreign.JCSP3DesKeyGenerator");
        map.put("KeyFactory.CP_RSA implementedIn", "Software");
        map.put("Alg.Alias.KeyFactory." + oid, "CP_RSA");
        map.put("Alg.Alias.KeyFactory.OID." + oid, "CP_RSA");
        map.put("KeyFactory.CP_RSA", "ru.CryptoPro.JCSP.Key.rsa.JCSPRSAKeyFactory");
        map.put("Cipher.AES", "ru.CryptoPro.JCSP.Cipher.foreign.AESCipher");
        map.put("Cipher.CP_AES", "ru.CryptoPro.JCSP.Cipher.foreign.AESCipher");
        map.put("Cipher.DES", "ru.CryptoPro.JCSP.Cipher.foreign.DESCipher");
        map.put("Cipher.CP_DES", "ru.CryptoPro.JCSP.Cipher.foreign.DESCipher");
        map.put("Cipher.3DES", "ru.CryptoPro.JCSP.Cipher.foreign.TripleDESCipher");
        map.put("Cipher.CP_3DES", "ru.CryptoPro.JCSP.Cipher.foreign.TripleDESCipher");
        map.put("Cipher.3DES_112", "ru.CryptoPro.JCSP.Cipher.foreign.TripleDESCipher");
        map.put("Cipher.CP_3DES_112", "ru.CryptoPro.JCSP.Cipher.foreign.TripleDESCipher");
        map.put("Cipher.DESede", "ru.CryptoPro.JCSP.Cipher.foreign.TripleDESCipher");
        map.put("Cipher.TripleDES", "ru.CryptoPro.JCSP.Cipher.foreign.TripleDESCipher");
        map.put("Cipher.RSA", "ru.CryptoPro.JCSP.Cipher.foreign.RSACipher");
        map.put("Cipher.CP_RSA", "ru.CryptoPro.JCSP.Cipher.foreign.RSACipher");
        map.put("AlgorithmParameters.GCM", "ru.CryptoPro.JCP.params.GCMParams");
        map.put("AlgorithmParameters.CP_GCM", "ru.CryptoPro.JCP.params.GCMParams");
        map.put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.6", GostCipher.STR_GCM_MODE);
        map.put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.26", GostCipher.STR_GCM_MODE);
        map.put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.46", GostCipher.STR_GCM_MODE);
        map.put("AlgorithmParameterGenerator.GCM", "ru.CryptoPro.JCP.params.GCMParams$GCMParamsGen");
        map.put("AlgorithmParameterGenerator.CP_GCM", "ru.CryptoPro.JCP.params.GCMParams$GCMParamsGen");
        map.put("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.1.6", GostCipher.STR_GCM_MODE);
        map.put("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.1.26", GostCipher.STR_GCM_MODE);
        map.put("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.1.46", GostCipher.STR_GCM_MODE);
    }
}
